import numpy as np

BINANCE_REST = "https://api.binance.com/api/v3/klines"
BINANCE_AGG_TRADES_REST = "https://api.binance.com/api/v3/aggTrades"
BINANCE_DEPTH_REST = "https://api.binance.com/api/v3/depth"
BINANCE_FUTURES_REST = "https://fapi.binance.com"

SECONDS_PER_BAR = 30
ANNUALIZATION_30S = np.sqrt(365 * 24 * 60 * 2)
DEFAULT_SYMBOL = "BTCUSDT"
DEFAULT_LOOKBACK_DAYS = 365
DEFAULT_PREDICT_LOOKBACK_MINUTES = 120
DEFAULT_THRESHOLD_30S = 0.0007
DEFAULT_CONFIDENCE = 0.60
DEFAULT_ENABLE_FUTURES_FEATURES = True
DEFAULT_ENABLE_DEPTH_FEATURES = True
DEFAULT_USE_GPU = False
DEFAULT_TUNE_TRIALS = 25
DEFAULT_OPTUNA_STORAGE = "optuna_studies.db"
DEFAULT_OPTUNA_STUDY_NAME = "btc_30s_xgb"
DEFAULT_USE_TRANSFORMER = True
DEFAULT_TRANSFORMER_SEQ_LEN = 120
DEFAULT_TRANSFORMER_EPOCHS = 12
DEFAULT_ENSEMBLE_WEIGHT_XGB = 0.55
DEFAULT_REQUIRE_MODEL_AGREEMENT = True
DEFAULT_FORCE_CONTINUOUS_TRADE = False
DEFAULT_MODEL_FILENAME = "ensemble_btc_30s.joblib"
MIN_TRAIN_BARS_30S = 20_000
